# Uses: https://github.com/cpeditor/cpeditor/blob/v6.2/.github/workflows/clang-format.yml

name: "Auto Clang Format"

on:
  push:
    paths-ignore:
      - '*.md'
      - '*/*.md'
      - '*/*/*.md'

jobs:
  build:
    name: "Auto Clang Format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install clang-format-9"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-9
    - name: "Format Codes"
      run: clang-format-9 -i */*.h */*/*.h
    - name: Commit files
      run: |
        git config --local user.email "clang-format-action@ccptl"
        git config --local user.name "clang-format bot"
        git diff-index --quiet HEAD || git commit -am "style: Format codes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
